### ISSUE TITLE
Black borders when screen is too wide

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixos-homepage#662] opened 2020-12-28 06:54 UTC
**Describe the glitch**
A clear and concise description of what the design glitch is.

So, I've got a new monitor and I'm having a little first world problem here:

**Screenshots**
Please provide screenshots that show your observation. Annotating them is a plus.

![image](https://user-images.githubusercontent.com/18599032/103194624-823f6900-48e0-11eb-99e1-d114bdcac0c1.png)

**Additional context**

**Comment by samueldr** [comment] 2020-12-28 08:43
It's by design.

Design elements can't cope with *too much* width. Without the black borders we'd be having other kind of issues with some of the "fancy" elements on page.

This is a situation where there's no good solution, every solution ends up annoying someone else for another reason :).

Maybe we can do something else than black bars, but it's... not really trivial either IIRC to do anything fancy with the way it's been done (Could be wrong, I forgot how it ended up being implemented).

**Comment by garbas** [comment] 2020-12-28 22:22
@Atemu Thank you for reporting issues. I know @samueldr did not provide the solution, but it is a compromise that we did. I'm going to close this issue since it is a known issue that is a compromise.

**Closed by garbas** 2020-12-28 22:22 UTC
Labels: design
