### ISSUE TITLE
Website in reload loop

### ISSUE THREAD

**Issue by poelzi** [NixOS/nixos-homepage#630] opened 2020-10-21 20:19 UTC
**Describe the glitch**
Since the redesign the website is **unusable** on Firefox due constant reloads.

**Additional context**

firefox 76.0.1 (64-bit). umatrix and ublock Origin active but everything allowed.

**Comment by garbas** [comment] 2020-10-22 19:03
@poelzi I'm not able to reproduce this. And I'm using the same addons as you are.

**Comment by garbas** [comment] 2020-11-27 15:21
I'm closing this since I can not reproduce it.

**Closed by garbas** 2020-11-27 15:21 UTC
Labels: bug
