### ISSUE TITLE
Links to “Nix expression” broken

### ISSUE THREAD

**Issue by rkoe** [NixOS/nixos-homepage#374] opened 2020-04-01 12:24 UTC
Currently, on https://nixos.org/nixos/packages.html, all links to “Nix expression” are broken.

- Currently, all links were removed and replaced by "Not specified"
- Some days ago, all links resulted in a 404 page.
  (e.g.  
  `https://github.com/NixOS/nixpkgs/blob/undefined//build/source/pkgs/applications/editors/vim/common.nix#L24`  
  instead of  
  `https://github.com/NixOS/nixpkgs/blob/ae48415e8b5f38cd72e17311369b9fdfabb16dde/pkgs/applications/editors/vim/common.nix`)

**Comment by edolstra** [comment] 2020-04-01 12:29
Closing as duplicate of #372.

**Closed by edolstra** 2020-04-01 12:29 UTC
