### ISSUE TITLE
Nixpkgs manual page loading very slow

### ISSUE THREAD

**Issue by andir** [NixOS/nixos-homepage#468] opened 2020-06-12 11:53 UTC
The [nixpkgs manual page](https://nixos.org/nixpkgs/manual/) seems to be loading extra slow these days.

In my observations that is not because of the size of the document but becaues of the CDN that fontawesome is using. Worst case it blocked the entire site from rendering for me. Observed this over multiple sessions. Here is just one example of how the network timings look like:

![firefoxm](https://user-images.githubusercontent.com/638836/84499750-76c58100-acb3-11ea-9a83-c55fc6cdbffe.png)

Proposed solution: Serve the fonts on our own. That might increase a bit of traffic that we (or rather Netilfy) is reeiving but also ensures that the user has a good experience when looking at the docs for the first time.

**Comment by flokli** [comment] 2020-06-12 12:39
![pic-20200612-143712](https://user-images.githubusercontent.com/183879/84503363-5d740300-acba-11ea-9882-03cef118479d.png)

I can confirm - in my case it's only one slow request, but delaying website loading by 4 seconds just to serve a webfont from a CDN seems counterproductive.

**Comment by garbas** [comment] 2020-09-24 22:21
Since this is related to fonts and serving them from netlify I will close this ticket since this is going to be addressed by #508

**Closed by garbas** 2020-09-24 22:21 UTC
Labels: bug, good first issue
