### ISSUE TITLE
Different logos for each project 

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixos-homepage#5] opened 2014-05-31 19:18 UTC
It would be awesome if there were a distinct logo for Nix, NixOS etc. 

Perhaps the mirrored lambda signs that make up the current logo could be used:
- nix is a single sign 
- nixpkgs is three signs, like a forest 
- nixos is the circle 
- nixops is intertwined circles like the Olympic rings 
- hydra is a circular tree of signs, like a plasma lightning disk

**Comment by Mathnerd314** [comment] 2015-11-21 23:00
https://github.com/qknight/Multi-PlatformSoftwarePackageManagement/blob/master/images/nix-collection.svg looks reasonable, it uses the old logo though.

**Comment by garbas** [comment] 2020-03-16 20:56
I'm closing this as a duplicate of #2. This issue talks about specific idea how to address general goal in #2.

**Closed by garbas** 2020-03-16 20:56 UTC
