### ISSUE TITLE
cover demo slide switch too fast

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixos-homepage#546] opened 2020-09-21 08:23 UTC
https://github.com/NixOS/nixos-homepage/blob/ce872344ac77f6d6e9f31e18215f079a0a6ee2cd/demos/cover.scenario#L22-L30

The slide switch after the last element is immediate, so you can’t see the result of the nix-shell nodejs command. cc @garbas

**Comment by Profpatsch** [comment] 2020-09-21 08:24
Looks like it’s the same for the other slides.

**Comment by garbas** [comment] 2020-09-21 08:26
Duplicate of#544

**Closed** 2020-09-21 08:27 UTC
Labels: duplicate
