### ISSUE TITLE
Why does "first steps" with NixOS on the main page lead to a dev environment tutorial?

### ISSUE THREAD

**Issue by Raikiri** [NixOS/nixos-homepage#825] opened 2022-04-11 11:42 UTC
**Introduce your stance**
As a new user, I was looking for information as to how to use the newly installed NixOS (how to configure basic stuff), etc, and naturally went to the NixOS's main page.

**Describe the issue**
On the main page there's a link to the "learn" page: https://nixos.org/learn.html that conveniently has a "first steps with nix" right after the "install nix" option. But this confusingly leads me to a dev environment setup tutorial which is definitely not going to be my first steps when I'm facing a freshly installed OS. I at least need to configure things such as keyboard layout, desktop environment, etc etc.

**Page links**
https://nixos.org/learn.html
https://nixos.org/guides/dev-environment.html

**Additional context**
I understand that setting up a dev environment can potentially be the first step right after installing Nix on an existing linux setup, but I expect the "first steps" on a NixOS webpage to lead to "first steps with NixOS". Or at least I expect the link to be named "dev environment setup with Nix".

- [ ] I already created a Pull Request

**Comment by fricklerhandwerk** [comment] 2022-06-06 22:04
fixed by #851

**Comment by Rosuavio** [comment] 2022-06-07 00:01
> @garbas fixed by #851 

@fricklerhandwerk, I don't believe that PR fixes this issue. I don't mean to speak for @Raikiri, but it seems that the issue is that @Raikiri is expecting the "first steps" to be "first steps after installing **NixOS**". While from the perspectives of experienced users it is clear that the content in the "Learn" page is always referring to **Nix** and not **NixOS**, newer users can get confused because they are not expecting **Nix** to specifically refer to the command line utility and **NixOS** to specifically refer to the operation system.

Since the "Learn" tab is accessible from the NixOS homepage (any many other pages), I think it's reasonable to expect users to assume that "Learn" refers to Nix, NixOS or both.

Possible solutions for this confusion are
- Rename the "Learn" tab to "Learn nix"
- Split the learn page into a sections labeled "NixOS" (containing NixOS related content) and "Nix" (containing Nix related content)
- Rename the "Learn" tab to "Learn nix" and add a "Learn NixOS" tab with NixOS related content.

**Comment by Raikiri** [comment] 2022-06-07 01:24
While I agree that having a more general setup for a development environment is better than having an arbitrarily chosen python environment, it does miss the point though: my first steps on a freshly installed system are definitely not going to be "creating a development environment" at all.

It's going to be questions like: "where are my configs?", "what's the basic examples of the nix config file?", "what do I install as a module and what do I install as a package and why?", "how do I update?", "what should I NOT do?", "how do imperative package management commands that I'm used to, map to nix's declarative paradigm?".

I know people often refer this set of basic questions to the general confusion created by a website that has "nixos" in the domain, but is actually referring to "nix" in its content. However, even when it comes to configuring nix itself, there seems to be lots of really basic "first steps" to learn prior to setting a development environment.

**Comment by fricklerhandwerk** [comment] 2022-09-01 16:41
@Raikiri @Rosuavio Does #891 address this issue? I will hopefully soon replace the NixOS logo graphics with one that only shows "Nix", to further reduce potential for confusion.

I know that nixos.org will then be mostly about Nix and not NixOS. We have an [open issue](https://github.com/NixOS/nix.dev/issues/287) that has to be addressed by the Foundation board and Nix marketing team to have a proper place serving NixOS.

**Comment by Raikiri** [comment] 2022-09-02 01:28
@fricklerhandwerk are the changes live already? Because as far as i can tell, all links in the "Learn" category on nixos.org website still lead to nix stuff. "First steps with NixOS" and "Learn how NixOS works" is still nowhere to be found.

I'd argue the current "first steps" article is not even what the majority of nix users expect: they don't expect to use it for development purposes at first, they expect to learn how to do basic things with it such as installing packages, modules, options -- that sort of stuff.

**Comment by fricklerhandwerk** [comment] 2022-09-02 11:25
@Raikiri as of today the [Learn](https://nixos.org/learn.html) page shows Nix instead of NixOS:

![Screenshot 2022-09-02 at 13 06 24](https://user-images.githubusercontent.com/6599296/188126687-e2102432-bf20-41bb-997a-eeede7ac4348.png)

That the "First steps with Nix" is titled "Ad hoc developer environments" but is really about, well, just "environments" is surely debatable. Feel free to [propose a change](https://github.com/NixOS/nix.dev/blob/master/source/tutorials/ad-hoc-developer-environments.md).

I suppose @domenkozar originally did that for SEO, and also, as said, we are currently [focused on software developers](https://github.com/NixOS/nixos-homepage/issues/828#issuecomment-1103838823). Hence we try to primarily [improve the onboarding experience for Nix](https://discourse.nixos.org/t/should-we-give-a-name-to-nix-on-non-nixos/21020/3).

I agree that the state of affairs is frustrating for NixOS enthusiasts, and would encourage you and everyone interested in fostering NixOS to set up a dedicated web site for NixOS. This obvioously requires significant effort and coordination, and apparently no one so far has been able to afford that. Still, if it works out, we can always add official branding and domain names.

**Comment by Narice** [comment] 2022-09-02 11:51
There are two distinct group of users in the Nix/OS community.
Users of the NixOS operating system and users of Nix.

Obviously, there are links between the two.
A person using NixOS will have to use Nix.

I'd argue that the graph proposed by @fricklerhandwerk should go in the other direction.
NixOS build onto the Nix Package Manager and Collection, and they themselves build on the Nix Language.

So the Nix Language is the source.
And here is one learning problem: All our tools uses the Nix Language, but learning the language is actually pretty tough as there are not a lot of resources on it. I don't mean Nix Pills, I mean a terse Nix Language Book and Reference.
The new Nix Manual is already a huge improvement, but is unfortunatly still not sufficient in my opinion.
How to really use the language, starting from no coding experience, or at least standard developer experience, that means, no functional programming knowledge in most cases.
It is a shame that in some ways this community is composed of I would say mostly functional programmers, that is a low overall percentage of the programming community.

A second problem that we have is that there are a lot of abstractions to learn and understand.
Modules, options, flakes, nix shells... And the abstractions used for one part of the community to an other are not the same, it depends widly on what you do with the Nix Language.
So building tutorials for each community is essential as the first steps will not be the same.

Thirdly, it is indeed better indeed to have the main website be about Nix, and I would say more precisely, Nix, the Package Manager. It is the cornerstone of every other tool and the reason why nixpkgs and the Nix Language exist.
As such, it is a great way of entry as everything else can be introduced in a resonable fashion.
An alternative to the "Nix" in the title would be "Nix/OS". I began using this after thinking that writing "Nix / NixOS" everywhere was very silly, and it seems appropiate to reconcile both parts of the community, without having to change the domain of the site.

Finally, building a community made website is a great thing, but having official documentation is a lot better.
I know and understand that resources are limited, but using a tool without having a good way of learning it is a hard journey.

**Comment by fricklerhandwerk** [comment] 2022-09-02 11:56
> All our tools uses the Nix Language, but learning the language is actually pretty tough as there are not a lot of resources on it.

@Narice My [Nix language tutorial](https://github.com/NixOS/nix.dev/pull/267/files) is waiting for reviews. I'd be happy to read your feedback.

**Comment by Narice** [comment] 2022-09-02 14:21
From what I can tell @fricklerhandwerk, your tutorial is awesome.
I din't read through the worked examples, but outside of that, that is a fantastic starter guide.
It doesn't cover everything that you need for writing in Nix, but it says so clearly and points people to resources for learning more: awesome.

**Comment by Narice** [comment] 2022-09-04 01:37
I just saw that your change is on nix.dev instead of being here, I'm not too familiar with the way this website is built, does it refer directly to the articles on nix.dev?
If so, why is nix.dev considered unofficial?

**Comment by fricklerhandwerk** [comment] 2022-09-06 13:59
Yes, nix.dev articles are included [here](https://github.com/NixOS/nixos-homepage/blob/02142b5ccafbf12b3526fc8723ea5042087a0e10/Makefile#L57), and unfortunately [still without attribution](https://github.com/NixOS/nixos-homepage/issues/671#issuecomment-791353841). I'd be happy if someone took the time to at least add a note and a link to the original, for example [here](https://github.com/NixOS/nixos-homepage/blob/02142b5ccafbf12b3526fc8723ea5042087a0e10/scripts/copy-nix-dev-tutorials.sh#L47), and would help getting it merges.

I opened a PR to [make nix.dev official](https://github.com/NixOS/nixos-homepage/pull/882), but there are still a few things in the way I can't do much about (see the comments there).

**Closed** 2023-04-18 17:56 UTC
Labels: content
