### ISSUE TITLE
I ran into this problem too. You can fix this by using `gpg --recv-keys`:

### ISSUE THREAD

**Issue by jess22664** [NixOS/nixos-homepage#539] opened 2020-09-18 02:52 UTC
I ran into this problem too. You can fix this by using `gpg --recv-keys`:

```
$ gpg --recv-keys B541D55301270E0BCF15CA5D8170B4726D7198DE
gpg: requesting key 6D7198DE from hkps server hkps.pool.sks-keyservers.net
gpg: key 6D7198DE: public key "Eelco Dolstra <edolstra@gmail.com>" imported
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   5  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 5u
gpg: next trustdb check due at 2018-08-19
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

$ gpg --verify install.sig install
gpg: Signature made Fri Jan 13 02:35:59 2017 PST using RSA key ID 6D7198DE
gpg: Good signature from "Eelco Dolstra <edolstra@gmail.com>" [unknown]
gpg:                 aka "Eelco Dolstra <eelco.dolstra@logicblox.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: B541 D553 0127 0E0B CF15  CA5D 8170 B472 6D71 98DE
```

_Originally posted by @gevans in https://github.com/NixOS/nixos-homepage/issues/111#issuecomment-275581972_

**Comment by garbas** [comment] 2020-09-24 16:08
This instruction is already on the download page.

I'm closing this since I don't know what the issue is, please reopen and explain what is the problem. Thank you.

**Closed by garbas** 2020-09-24 16:08 UTC
Labels: bug
